artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/viveknaidu007/end-to-end-ml-project-red-wine/blob/base/research/winequality-red.csv
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion